name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPOSITORY: ZhangYHe/ZhangYHe
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_TITLE: true
          STOP_AT_OTHER: false
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka"
          COMMIT_MESSAGE: "Updated simple waka stats section"
          BLOCKS: "░▒▓█"
          TIME_RANGE: all_time
          LANG_COUNT: 10
          IGNORED_LANGUAGES: JSON Text YAML TOML Markdown
          
    
